# Pinned configuration for reproducibility
exporter.fhir.export = true
exporter.fhir.version = R4
exporter.years_of_history = 10
exporter.baseDirectory = ./synthea/output
generate.only_alive_patients = false
generate.append_numbers_to_person_names = false
